---
- name:      Ensure git package is present
  package:
    name:    git
    state:   present

- name:      Ensure kubectx repository is cloned from GitHub
  git:
    repo:    "{{ source_url }}/{{ github_namespace }}"
    dest:    "{{ kubectx_installation_path }}"
    version: "{{ kubectx_version }}"

- name:      Ensure kubectx and kubens links are created
  file:
    src:     "{{ kubectx_installation_path }}/{{ item }}"
    dest:    "/usr/local/bin/{{ item }}"
    state:   link
  loop:
    - kubens
    - kubectx
